services:
  app:
    image: 'webdevops/php-nginx:8.2'
    container_name: cw2-app-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - '8000:80'
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    depends_on:
      - db

  db:
    image: 'mysql:8.0'
    container_name: cw2-backend-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chicken
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: cw2-backend-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  dbdata:
